FORMAT: 1A
HOST: http://inttest.apiblueprint.org/

# int API

It's Ninja Time application API

## Events Collection [/api/events/{eventid}]

+ Parameters
    + eventid (number) - Unique identifier of the event

### List all events [GET /api/events]

+ Response 200 (application/json)
    + Attributes
        - events (array[EventSummary])

### Get a single event [GET /api/events/{eventid}]

+ Response 200 (application/json)
    + Attributes
        - event (EventSummary)
        - participants (array[EventParticipant])
        - stages (array[EventStage])
        - obstacles (array[EventObstacle])

+ Response 404

### Modify event details [PUT /api/events/{eventid}]

+ Request (application/json)
    + Attributes (EventDetailsUpdate)

+ Response 204

+ Response 400 (application/json)
    + Attributes (Error400)

+ Response 404

## Event Obstacle Collection [/api/events/{eventid}/obstacles]

+ Parameters
    + eventid (number) - Unique identifier of the event

### Add an event obstacle [POST /api/events/{eventid}/obstacles]

+ Request (application/json)
    + Attributes (EventObstacleCreate)

+ Response 200
    + Attributes (EventObstacleCreateResponse)

+ Response 404

+ Response 400 (application/json)
    + Attributes (Error400)

### Modify an event obstacle [PUT /api/events/{eventid}/obstacles/{obstacleid}]

+ Parameters
    + obstacleid (number) - Unique identifier of the obstacle

+ Request (application/json)
    + Attributes (EventObstacleModify)

+ Response 204

+ Response 404

+ Response 400 (application/json)
    + Attributes (Error400)

### Remove an event obstacle [DELETE /api/events/{eventid}/obstacles/{obstacleid}]

+ Parameters
    + obstacleid (number) - Unique identifier of the obstacle

+ Response 204

+ Response 404

+ Response 400 (application/json)
    + Attributes (Error400)

## Event Participant Collection [/api/events/{eventid}/participants]

+ Parameters
    + eventid (number) - Unique identifier of the event

### Add an event participant [POST /api/events/{eventid}/participants]

+ Request (application/json)
    + Attributes (EventParticipantCreate)

+ Response 200
    + Attributes (EventParticipantCreateResponse)

+ Response 404

+ Response 400 (application/json)
    + Attributes (Error400)

### Modify an event participant [PUT /api/events/{eventid}/participants/{participantid}]

+ Parameters
    + participantid (number) - Unique identifier of the participant in the event

+ Request (application/json)
    + Attributes (EventParticipantModify)

+ Response 204

+ Response 404

+ Response 400 (application/json)
    + Attributes (Error400)

### Remove an event participant [DELETE /api/events/{eventid}/participants/{participantid}]

+ Parameters
    + participantid (number) - Unique identifier of the participant in the event

+ Response 204

+ Response 404

+ Response 400 (application/json)
    + Attributes (Error400)

## Stages Collection [/api/events/{eventid}/stages/{stageid}]

+ Parameters
    + eventid (number) - Unique identifier of the event
    + stageid (number) - Unique identifier of the stage

### Get a single stage [GET /api/events/{eventid}/stages/{stageid}]

+ Response 200 (application/json)
    + Attributes
        - details (EventStage)
        - obstacles (array[StageObstacle])
        - upcoming (array[UpcomingRun])
        - finished (array[FinishedRun])

+ Response 404

## Stage Obstacles [/api/events/{eventid}/stages/{stageid}/obstacles]

+ Parameters
    + eventid (number) - Unique identifier of the event
    + stageid (number) - Unique identifier of the stage

### List all stage obstacles [GET /api/events/{eventid}/stages/{stageid}/obstacles]

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes
        - obstacles (array[StageObstacle])

+ Response 404

## Stage Results [/api/events/{eventid}/stages/{stageid}/results]

+ Parameters
    + eventid (number) - Unique identifier of the event
    + stageid (number) - Unique identifier of the stage

### List current stage results [GET /api/events/{eventid}/stages/{stageid}/results]

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes
        - details (EventStage)
        - results (array[StageResult])

+ Response 404

### Remove a single stage result [DELETE /api/events/{eventid}/stages/{stageid}/results/{runid}]
+ Parameters
    + runid (number) - Unique identifier of this run result

+ Response 204

+ Response 404

+ Response 400 (application/json)
    + Attributes (Error400)



# Data Structures

## EventSummary (object)
- EventId: 5 (number) - Unique Id of the event
- Name: `Sample Ninja Event` (string) - Viewed name of event
- StartDate: `2018-10-10` (string) - Date only when it starts
- Location: `Sample Location` (string) - Free text location description
- Description: `Sample Description` (string) - Free text to describe anything else about your event
- ParticipantCount: 20 (number) - How many participants we currently have
- StageCount: 4 (number) - Total count of stages
- ActiveStageId: 9 (number) - Unique Id of the active stage.  First stage if event is to come.  Null if unstarted or done - see also Completed
- ActiveStageName: `Stage 1` (string) - Name of the ActiveStageId or blank
- Completed: false (boolean) - Has the event been completed?

## EventDetailsUpdate (object)
- Name: `Sample Ninja Event` (string) - Viewed name of event
- StartDate: `2018-10-10` (string) - Date only when it starts
- Location: `Sample Location` (string) - Free text location description
- Description: `Sample Description` (string) - Free text to describe anything else about your event

## EventParticipant (object)
- Id: 4 (number) - Unique Id of the participant in this event
- Name: `Don Thompson` (string) - Name of participant

## EventStage (object)
- StageId: 9 (number) - Unique Id of the stage
- StageName: `Stage 1` (string) - Name of the stage.  Typically Stage 1, Stage 2, etc.
- StageOrder: 1 (number) - Numeric order of the stages in the event
- EventId: 5 (number) - Unique Id of the event this stage is part of
- EventName: `Sample Ninja Event` (string) - Viewed name of the event this stage is part of
- ObstacleCount: 6 (number) - Count of obstacles assigned to this stage

## EventObstacle (object)
- ObstacleId: 13 (number) - Unique Id of this obstacle
- Name: `Warped Wall` (string) - Name of this obstacle
- Description: `A very tall curved wall` (string) -  A description of the obstacle

## StageObstacle (object)
- ObstacleId: 13 (number) - Unique Id of this obstacle
- Name: `Warped Wall` (string) - Name of this obstacle
- Order: 1 (number) - Unique Id of the stage this obstacle is part of
- Description: `A very tall curved wall` (string) -  A description of the obstacle

## UpcomingRun (object)
- RunId: 1 (number) - Unique Id of this run
- Participant (EventParticipant) - The participant details
- Order: 6 (number) - Order of this run in the stage - ordered from the beginning of the stage, not the remaining

## RunResultSummary (object)
- NumObstaclesCompleted: 6 (number) - Count of obstacles passed in this result
- RunTime: 84.15 (number) - Total run time to success or failure in seconds.  May include decimal seconds

## FinishedRun (object)
- RunId: 1 (number) - Unique Id of this run
- Participant (EventParticipant) - The participant details
- Order: 6 (number) - Order of this run in the stage - ordered from the beginning of the stage, not the remaining
- Result (RunResultSummary) - Time and number of obstacles finished

## StageResult (object)
- RunId: 42 (number) - Unique Id of this result among all results
- Participant (EventParticipant) - The participant details
- Order: 6 (number) - Order of this run in the stage
- Place: 3 (number) - Finishing place in this stage.  Ordered by number completed descending then time ascending
- Result (RunResultSummary) - Time and number of obstacles finished

## Error400 (object)
- message: `An error has occurred` (string)

## EventParticipantCreate (object)
- Name: `Don Thompson` (string) - Name of the participant

## EventParticipantModify (object)
- Name: `Don Thompson` (string) - Name of the participant

## EventParticipantCreateResponse (object)
- Participant (EventParticipant)

## EventObstacleCreate (object)
- Name: `Warped Wall` (string) - Short name of the obstacle
- Description: `A very tall curved wall` (string) -  A description of the obstacle

## EventObstacleModify (object)
- Name: `Warped Wall` (string) - Short name of the obstacle
- Description: `A very tall curved wall` (string) -  A description of the obstacle

## EventObstacleCreateResponse (object)
- Obstacle (EventObstacle)