FORMAT: 1A
HOST: http://inttest.apiblueprint.org/

# int TEST API

A test API to play with apiary.


## Events Collection [/event]

### List All Events [GET]
Descriptive text here

+ Response 200 (application/json)

        [
            {
                id: 1,
                name: "Sample Event 1"
            },
            {
                id: 2,
                name: "Sample Event 2"
            }
        ]

### Get Single Event [GET /event/{id}]

+ Parameters
    + id (string)

+ Response 200 (application/json)

        {
            id: 1,
            name: "Sample Event 1"
        }

### Create an Event [POST]

+ Request (application/json)

        {
            name: "Event Name Here"
        }

+ Response 201 (application/json)

        {
            id:  123
        }

### Update an Event [PUT]

+ Request (application/json)

        {
            name: "Event Name Here"
        }

+ Response 204

### Delete an Event [DELETE]

+ Request (application/json)

        {
            id: 123
        }

+ Response 204
